---
title: "Funding"
---

Ruth does not typically accept students into the lab without being able to guarantee at least five years of funding. At Bren, five-year funding plans for PhD students are highly individualized. These can include a combination of external fellowships, internal fellowships, grants, donor funds, and academic employment (like Teaching Assistantships and Graduate Student Researcher positions). 

You are encouraged to apply for external funding through graduate scholarships and fellowships, like:

- NSF Graduate Research Fellowship Program (NSF GRFP)
- Ford Foundation
- GEM Fellowship
- NASA Future Investigators in NASA Earth and Space Science and Technology (FINESST)
- Department of Energy Computational Science Graduate Fellowship (DOE CSGF) 

Additional resources like [the Society of Conservation Biology's opportunity document](https://docs.google.com/document/d/1-xF9qw2B2hirk5MpNRICv_M3tZZOAHJnO-UmdT-ZSuw/edit?tab=t.0) exist.

Ruth will also share funding opportunities as they come up, either to the group or in individual meetings.
